// The themed-icon layer: a flat அ silhouette as Android vector pathData.
//
// Android 13+ tints a `monochrome` drawable to the user's wallpaper palette. It is a SILHOUETTE by
// definition — one colour, no gradients, no brushwork — so the painted artwork cannot be used here
// and must not be: a themed icon made from a tinted painting is a smudge.
//
// A letterform is exactly right for this, so the outline comes from the font rather than from the
// art. This is safe to re-run in a way the old icon generator was not: it produces ONE layer that
// is meant to be a plain outline, and it cannot touch the supplied artwork.
//
// Geometry: Android's adaptive canvas is 108x108dp with a 66dp safe circle in the middle. The glyph
// is fitted to 46dp so it clears that circle comfortably even under an aggressive OEM mask.
//
// Usage: swift tools/android/make_monochrome.swift > android/app/src/main/res/drawable/ic_launcher_monochrome.xml
//
// spine: C4
import AppKit
import CoreText
import Foundation

let canvas: CGFloat = 108, target: CGFloat = 46

func glyphPath(_ s: String, font: String) -> CGPath {
    let f = CTFontCreateWithName(font as CFString, 700, nil)
    let line = CTLineCreateWithAttributedString(NSAttributedString(string: s, attributes: [.font: f]))
    let path = CGMutablePath()
    for run in (CTLineGetGlyphRuns(line) as! [CTRun]) {
        let rf = unsafeBitCast(CFDictionaryGetValue(CTRunGetAttributes(run),
                    Unmanaged.passUnretained(kCTFontAttributeName).toOpaque()), to: CTFont.self)
        let n = CTRunGetGlyphCount(run)
        var g = [CGGlyph](repeating: 0, count: n), p = [CGPoint](repeating: .zero, count: n)
        CTRunGetGlyphs(run, CFRangeMake(0, n), &g); CTRunGetPositions(run, CFRangeMake(0, n), &p)
        for i in 0..<n {
            guard let gp = CTFontCreatePathForGlyph(rf, g[i], nil) else { continue }
            path.addPath(gp, transform: CGAffineTransform(translationX: p[i].x, y: p[i].y))
        }
    }
    return path
}

let raw = glyphPath("அ", font: "Tamil MN Bold")
let b = raw.boundingBox
let scale = target / max(b.width, b.height)
// Y is flipped: Core Graphics counts up from the bottom, Android vectors count down from the top.
var t = CGAffineTransform.identity
    .translatedBy(x: canvas / 2, y: canvas / 2)
    .scaledBy(x: scale, y: -scale)
    .translatedBy(x: -b.midX, y: -b.midY)
let fitted = raw.copy(using: &t)!

func f(_ v: CGFloat) -> String {
    let r = (v * 100).rounded() / 100
    return r == r.rounded() ? String(Int(r)) : String(format: "%g", Double(r))
}

var d = ""
fitted.applyWithBlock { e in
    let p = e.pointee.points
    switch e.pointee.type {
    case .moveToPoint:         d += "M\(f(p[0].x)),\(f(p[0].y)) "
    case .addLineToPoint:      d += "L\(f(p[0].x)),\(f(p[0].y)) "
    case .addQuadCurveToPoint: d += "Q\(f(p[0].x)),\(f(p[0].y)) \(f(p[1].x)),\(f(p[1].y)) "
    case .addCurveToPoint:     d += "C\(f(p[0].x)),\(f(p[0].y)) \(f(p[1].x)),\(f(p[1].y)) \(f(p[2].x)),\(f(p[2].y)) "
    case .closeSubpath:        d += "Z "
    @unknown default: break
    }
}

print("""
<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by tools/android/make_monochrome.swift. Do not hand-edit; regenerate.

     The themed-icon layer (Android 13+), which the system tints to the wallpaper palette. It is a
     silhouette by definition, so it is the letterform from the font rather than the painted
     artwork — a tinted painting is a smudge. அ fitted to \(f(target))dp inside the 108dp canvas,
     which keeps it clear of the 66dp safe circle under any OEM mask. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
    <path android:fillColor="#FFFFFFFF" android:fillType="nonZero"
        android:pathData="\(d.trimmingCharacters(in: .whitespaces))" />
</vector>
""")
