#!/usr/bin/env python3
"""Compliance Leaf generator: Spine commitment → feature → test.

Scans code, config and tests for `spine: C<n>` tags (a tag line may list several: `spine: C1, C7`).
Writes leaves/compliance/TRACEABILITY.md.

Exit codes:
  1  a tag names a commitment the Spine does not have (always fatal)
  2  --strict and a commitment has no tagged implementation or no tagged test (release gate)

Also reports, without failing, source files under android/*/src/main that carry no tag at all:
each is either plumbing that should name the commitment it serves, or scope creep.
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "leaves/compliance/TRACEABILITY.md"
SKIP = {"build", ".gradle", ".cxx", "third_party", "models", "leaves", ".git", ".kotlin", "bin"}
EXTS = {".kt", ".kts", ".cpp", ".h", ".xml", ".sh", ".py"}
TAG = re.compile(r"spine:\s*((?:C\d+)(?:\s*,\s*C\d+)*)")
TEST_MARKERS = ("/src/test/", "/src/androidTest/", "tools/host/", "tools/check_", "tools/zip_entry",
                "tools/verify_", "tools/bench", "tools/release_check")
SELF = {"tools/trace.py"}
strict = "--strict" in sys.argv[1:]

spine = (ROOT / "SPINE.md").read_text()
version = re.search(r"spine_version:\s*([\d.]+)", spine).group(1)
commitments = dict(re.findall(r"^\| \*\*(C\d+)\*\* \| (.+?) \|$", spine, re.M))

def is_test(p: pathlib.Path) -> bool:
    s = "/" + p.as_posix()
    return any(k in s for k in TEST_MARKERS)

features = {c: [] for c in commitments}
tests = {c: [] for c in commitments}
unknown, untagged_main = [], []
for p in sorted(ROOT.rglob("*")):
    rel = p.relative_to(ROOT)
    if p.is_dir() or p.suffix not in EXTS or SKIP & set(rel.parts) or rel.as_posix() in SELF:
        continue
    tagged = False
    for n, line in enumerate(p.read_text(errors="ignore").splitlines(), 1):
        for m in TAG.finditer(line):
            tagged = True
            for cid in re.findall(r"C\d+", m.group(1)):
                ref = f"`{rel.as_posix()}:{n}`"
                if cid not in commitments:
                    unknown.append(f"{ref} → {cid}")
                    continue
                (tests if is_test(rel) else features)[cid].append(ref)
    s = rel.as_posix()
    if not tagged and s.startswith("android/") and "/src/main/" in s and p.suffix in {".kt", ".cpp", ".h"}:
        untagged_main.append(f"`{s}`")

rows, gaps = [], []
for cid, text in commitments.items():
    f, t = sorted(set(features[cid])), sorted(set(tests[cid]))
    if not f: gaps.append(f"**{cid}** has no tagged implementation")
    if not t: gaps.append(f"**{cid}** has no tagged test or verification")
    rows.append(f"| **{cid}** | {text} | {'<br>'.join(f) or '**GAP**'} | {'<br>'.join(t) or '**GAP**'} |")

md = [
    "<!-- generated by tools/trace.py — do not edit; re-run after any Spine or code change -->",
    "# Compliance Leaf — traceability matrix",
    "",
    f"spine_version: {version}",
    "",
    "Store-policy status per commitment lives in `play-policy-checklist.md`; licence obligations in `licence-audit.md`.",
    "A tagged test proves the *mechanism* exists, not that Play will accept it — read the checklist for C9.",
    "",
    "| Commitment | Spine text | Implemented in | Verified by |",
    "|---|---|---|---|",
    *rows,
    "",
    "## Gaps",
    "",
    *([f"- {g}" for g in gaps] or ["None."]),
    "",
    "## Tags naming commitments the Spine does not have",
    "",
    *([f"- {u}" for u in unknown] or ["None."]),
    "",
    "## Untagged main-source files (possible scope creep, or missing tag)",
    "",
    "Not a failure. Each should either carry the `spine: C<n>` of the commitment it serves, or be questioned.",
    "",
    *([f"- {u}" for u in untagged_main] or ["None."]),
    "",
]
OUT.write_text("\n".join(md))
print(f"{len(commitments)} commitments, {len(gaps)} gaps, {len(unknown)} unknown tags, "
      f"{len(untagged_main)} untagged main sources → {OUT.relative_to(ROOT)}")
if unknown:
    sys.exit(1)
if strict and gaps:
    sys.exit(2)
